config/routes.rb
Rails.application.routes.draw do

  resources :text_messages
  get '/text' => "home#index"
  post '/send_text' => "home#send_text"
  Rails.application.routes.draw do
  post 'test' => 'test#index'

end

app/models/text_message.rb
class TextMessage < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token

  def index
    @stuff_for_view = "Test"
  end

  def send_text
    TextMessage.create(:message => params[:message], :number => params[:number])
    puts params
  end

end

app/controllers/test_controller.rb
class TestController < ApplicationController
skip_before_action :verify_authenticity_token

def index

t = Tropo::Generator.new
t.say(:value => "Hello World!")
render :json => t.response
end

end

app/controllers/text_messages_controller.rb
class TextMessagesController < ApplicationController
  before_action :set_text_message, only: [:show, :edit, :update, :destroy]

  # GET /text_messages
  # GET /text_messages.json
  def index
    @text_messages = TextMessage.all
  end

  # GET /text_messages/1
  # GET /text_messages/1.json
  def show
  end

  # GET /text_messages/new
  def new
    @text_message = TextMessage.new
  end

  # GET /text_messages/1/edit
  def edit
  end

  # POST /text_messages
  # POST /text_messages.json
  def create
    @text_message = TextMessage.new(text_message_params)

    respond_to do |format|
      if @text_message.save
        format.html { redirect_to @text_message, notice: 'Text message was successfully created.' }
        format.json { render :show, status: :created, location: @text_message }
      else
        format.html { render :new }
        format.json { render json: @text_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /text_messages/1
  # PATCH/PUT /text_messages/1.json
  def update
    respond_to do |format|
      if @text_message.update(text_message_params)
        format.html { redirect_to @text_message, notice: 'Text message was successfully updated.' }
        format.json { render :show, status: :ok, location: @text_message }
      else
        format.html { render :edit }
        format.json { render json: @text_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /text_messages/1
  # DELETE /text_messages/1.json
  def destroy
    @text_message.destroy
    respond_to do |format|
      format.html { redirect_to text_messages_url, notice: 'Text message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_text_message
      @text_message = TextMessage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def text_message_params
      params.require(:text_message).permit(:message, :number, :user_id, :organization_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/text_messages_helper.rb
module TextMessagesHelper
end

app/views/home/index.html.erb
<form method="POST" action="/send_text">
  To Number:<br>
  <input type="text" name="number" value=""><br>
  Text Message:<br>
  <input type="text" name="message" value=""><br><br>
  <input type="submit" value="Send Text Message">
</form>

app/views/home/send_text.html.erb
<p>You have sent your text message to <%= params[:number] %>!<p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Helloworld</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/text_messages/_form.html.erb
<%= form_for(@text_message) do |f| %>
  <% if @text_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@text_message.errors.count, "error") %> prohibited this text_message from being saved:</h2>

      <ul>
      <% @text_message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :organization_id %><br>
    <%= f.number_field :organization_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/text_messages/edit.html.erb
<h1>Editing Text Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @text_message %> |
<%= link_to 'Back', text_messages_path %>

app/views/text_messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Text Messages</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>Number</th>
      <th>User</th>
      <th>Organization</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @text_messages.each do |text_message| %>
      <tr>
        <td><%= text_message.message %></td>
        <td><%= text_message.number %></td>
        <td><%= text_message.user_id %></td>
        <td><%= text_message.organization_id %></td>
        <td><%= link_to 'Show', text_message %></td>
        <td><%= link_to 'Edit', edit_text_message_path(text_message) %></td>
        <td><%= link_to 'Destroy', text_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Text message', new_text_message_path %>

app/views/text_messages/new.html.erb
<h1>New Text Message</h1>

<%= render 'form' %>

<%= link_to 'Back', text_messages_path %>

app/views/text_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @text_message.message %>
</p>

<p>
  <strong>Number:</strong>
  <%= @text_message.number %>
</p>

<p>
  <strong>User:</strong>
  <%= @text_message.user_id %>
</p>

<p>
  <strong>Organization:</strong>
  <%= @text_message.organization_id %>
</p>

<%= link_to 'Edit', edit_text_message_path(@text_message) %> |
<%= link_to 'Back', text_messages_path %>